// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	videoStatFieldNames          = builder.RawFieldNames(&VideoStat{})
	videoStatRows                = strings.Join(videoStatFieldNames, ",")
	videoStatRowsExpectAutoSet   = strings.Join(stringx.Remove(videoStatFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	videoStatRowsWithPlaceHolder = strings.Join(stringx.Remove(videoStatFieldNames, "`video_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePilipiliVideoVideoStatVideoIdPrefix = "cache:pilipiliVideo:videoStat:videoId:"
)

type (
	videoStatModel interface {
		Insert(ctx context.Context, data *VideoStat) (sql.Result, error)
		FindOne(ctx context.Context, videoId int64) (*VideoStat, error)
		Update(ctx context.Context, data *VideoStat) error
		Delete(ctx context.Context, videoId int64) error
	}

	defaultVideoStatModel struct {
		sqlc.CachedConn
		table string
	}

	VideoStat struct {
		VideoId       int64     `db:"video_id"`       // 关联的视频ID
		ViewCount     int64     `db:"view_count"`     // 总播放量
		DanmakuCount  int64     `db:"danmaku_count"`  // 总弹幕数
		ReplyCount    int64     `db:"reply_count"`    // 总评论数
		LikeCount     int64     `db:"like_count"`     // 点赞数
		CoinCount     int64     `db:"coin_count"`     // 投币数
		FavoriteCount int64     `db:"favorite_count"` // 收藏数
		ShareCount    int64     `db:"share_count"`    // 分享数
		UpdateTime    time.Time `db:"update_time"`    // 最后同步时间
	}
)

func newVideoStatModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultVideoStatModel {
	return &defaultVideoStatModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`video_stat`",
	}
}

func (m *defaultVideoStatModel) Delete(ctx context.Context, videoId int64) error {
	pilipiliVideoVideoStatVideoIdKey := fmt.Sprintf("%s%v", cachePilipiliVideoVideoStatVideoIdPrefix, videoId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `video_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, videoId)
	}, pilipiliVideoVideoStatVideoIdKey)
	return err
}

func (m *defaultVideoStatModel) FindOne(ctx context.Context, videoId int64) (*VideoStat, error) {
	pilipiliVideoVideoStatVideoIdKey := fmt.Sprintf("%s%v", cachePilipiliVideoVideoStatVideoIdPrefix, videoId)
	var resp VideoStat
	err := m.QueryRowCtx(ctx, &resp, pilipiliVideoVideoStatVideoIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `video_id` = ? limit 1", videoStatRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, videoId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVideoStatModel) Insert(ctx context.Context, data *VideoStat) (sql.Result, error) {
	pilipiliVideoVideoStatVideoIdKey := fmt.Sprintf("%s%v", cachePilipiliVideoVideoStatVideoIdPrefix, data.VideoId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, videoStatRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.VideoId, data.ViewCount, data.DanmakuCount, data.ReplyCount, data.LikeCount, data.CoinCount, data.FavoriteCount, data.ShareCount)
	}, pilipiliVideoVideoStatVideoIdKey)
	return ret, err
}

func (m *defaultVideoStatModel) Update(ctx context.Context, data *VideoStat) error {
	pilipiliVideoVideoStatVideoIdKey := fmt.Sprintf("%s%v", cachePilipiliVideoVideoStatVideoIdPrefix, data.VideoId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `video_id` = ?", m.table, videoStatRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ViewCount, data.DanmakuCount, data.ReplyCount, data.LikeCount, data.CoinCount, data.FavoriteCount, data.ShareCount, data.VideoId)
	}, pilipiliVideoVideoStatVideoIdKey)
	return err
}

func (m *defaultVideoStatModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePilipiliVideoVideoStatVideoIdPrefix, primary)
}

func (m *defaultVideoStatModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `video_id` = ? limit 1", videoStatRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultVideoStatModel) tableName() string {
	return m.table
}
