// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateCommentReq struct {
	UserId    int64  `json:"userId"`
	ArticleId int64  `json:"articleId"`
	Content   string `json:"content"`
}

type CreateCommentResp struct {
	CommentId int64 `json:"commentId"`
}

type GetUserInfoReq struct {
	Id int64 `form:"id"`
}

type GetUserInfoResp struct {
	Id       int64  `json:"id"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}
