// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: grpcdemo.proto

package moretestfromaccount2order

import (
	"context"

	"grpcdemo/grpcdemo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Order     = grpcdemo.Order
	OrderItem = grpcdemo.OrderItem
	Orders    = grpcdemo.Orders
	User      = grpcdemo.User

	MoreTestFromAccount2Order interface {
		GetMyOrder(ctx context.Context, in *User, opts ...grpc.CallOption) (*Orders, error)
	}

	defaultMoreTestFromAccount2Order struct {
		cli zrpc.Client
	}
)

func NewMoreTestFromAccount2Order(cli zrpc.Client) MoreTestFromAccount2Order {
	return &defaultMoreTestFromAccount2Order{
		cli: cli,
	}
}

func (m *defaultMoreTestFromAccount2Order) GetMyOrder(ctx context.Context, in *User, opts ...grpc.CallOption) (*Orders, error) {
	client := grpcdemo.NewMoreTestFromAccount2OrderClient(m.cli.Conn())
	return client.GetMyOrder(ctx, in, opts...)
}
