// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	private "pilipili/app/video/api/internal/handler/private"
	public "pilipili/app/video/api/internal/handler/public"
	"pilipili/app/video/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// UP主投稿视频
				Method:  http.MethodPost,
				Path:    "/video/v1/publish",
				Handler: private.PublishHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取视频详情
				Method:  http.MethodGet,
				Path:    "/video/v1/detail/:id",
				Handler: public.DetailHandler(serverCtx),
			},
			{
				// 首页推荐视频流
				Method:  http.MethodGet,
				Path:    "/video/v1/feed",
				Handler: public.FeedHandler(serverCtx),
			},
			{
				// 获取真实的视频流媒体播放地址
				Method:  http.MethodGet,
				Path:    "/video/v1/play/:id",
				Handler: public.PlayHandler(serverCtx),
			},
		},
	)
}
