// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Author struct {
	Id       int64  `json:"id"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type DetailReq struct {
	Id int64 `path:"id"`
}

type DetailResp struct {
	Id         int64  `json:"id"`
	Title      string `json:"title"`
	Summary    string `json:"summary"`
	CoverUrl   string `json:"coverUrl"`
	CategoryId int32  `json:"categoryId"`
	Author     Author `json:"author"`
	Stat       Stat   `json:"stat"`
}

type FeedReq struct {
	CategoryId int32 `form:"categoryId,default=0"` // 0表示全站推荐
	Cursor     int64 `form:"cursor,default=0"`     // 游标分页 (防数据重复)
	Limit      int   `form:"limit,default=20"`     // 每页数量
}

type FeedResp struct {
	List   []VideoCard `json:"list"`
	Cursor int64       `json:"cursor"` // 下一页的游标
	IsEnd  bool        `json:"isEnd"`  // 是否到底了
}

type PlayReq struct {
	Id           int64  `path:"id"`
	QualityLimit string `form:"qualityLimit,optional"` // 请求画质 1080P/720P
}

type PlayResp struct {
	Streams []StreamInfo `json:"streams"`
}

type PublishReq struct {
	Title      string `json:"title"`
	CoverUrl   string `json:"coverUrl"`
	VideoUrl   string `json:"videoUrl"`
	CategoryId int32  `json:"categoryId"`
	Summary    string `json:"summary"`
}

type PublishResp struct {
	VideoId int64 `json:"videoId"`
}

type Stat struct {
	ViewCount    int64 `json:"viewCount"`
	DanmakuCount int64 `json:"danmakuCount"`
	ReplyCount   int64 `json:"replyCount"`
	LikeCount    int64 `json:"likeCount"`
	CoinCount    int64 `json:"coinCount"`
}

type StreamInfo struct {
	Quality string `json:"quality"`
	Format  string `json:"format"`
	Url     string `json:"url"`
}

type VideoCard struct {
	Id          int64  `json:"id"`
	Title       string `json:"title"`
	CoverUrl    string `json:"coverUrl"`
	AuthorName  string `json:"authorName"`
	ViewCount   int64  `json:"viewCount"`
	PublishTime int64  `json:"publishTime"`
}
