// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: grpcdemo.proto

package grpcdemo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MoreTestFromAccount2Order_GetMyOrder_FullMethodName = "/grpcdemo.MoreTestFromAccount2Order/getMyOrder"
)

// MoreTestFromAccount2OrderClient is the client API for MoreTestFromAccount2Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoreTestFromAccount2OrderClient interface {
	GetMyOrder(ctx context.Context, in *User, opts ...grpc.CallOption) (*Orders, error)
}

type moreTestFromAccount2OrderClient struct {
	cc grpc.ClientConnInterface
}

func NewMoreTestFromAccount2OrderClient(cc grpc.ClientConnInterface) MoreTestFromAccount2OrderClient {
	return &moreTestFromAccount2OrderClient{cc}
}

func (c *moreTestFromAccount2OrderClient) GetMyOrder(ctx context.Context, in *User, opts ...grpc.CallOption) (*Orders, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Orders)
	err := c.cc.Invoke(ctx, MoreTestFromAccount2Order_GetMyOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoreTestFromAccount2OrderServer is the server API for MoreTestFromAccount2Order service.
// All implementations must embed UnimplementedMoreTestFromAccount2OrderServer
// for forward compatibility.
type MoreTestFromAccount2OrderServer interface {
	GetMyOrder(context.Context, *User) (*Orders, error)
	mustEmbedUnimplementedMoreTestFromAccount2OrderServer()
}

// UnimplementedMoreTestFromAccount2OrderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMoreTestFromAccount2OrderServer struct{}

func (UnimplementedMoreTestFromAccount2OrderServer) GetMyOrder(context.Context, *User) (*Orders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyOrder not implemented")
}
func (UnimplementedMoreTestFromAccount2OrderServer) mustEmbedUnimplementedMoreTestFromAccount2OrderServer() {
}
func (UnimplementedMoreTestFromAccount2OrderServer) testEmbeddedByValue() {}

// UnsafeMoreTestFromAccount2OrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoreTestFromAccount2OrderServer will
// result in compilation errors.
type UnsafeMoreTestFromAccount2OrderServer interface {
	mustEmbedUnimplementedMoreTestFromAccount2OrderServer()
}

func RegisterMoreTestFromAccount2OrderServer(s grpc.ServiceRegistrar, srv MoreTestFromAccount2OrderServer) {
	// If the following call pancis, it indicates UnimplementedMoreTestFromAccount2OrderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MoreTestFromAccount2Order_ServiceDesc, srv)
}

func _MoreTestFromAccount2Order_GetMyOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoreTestFromAccount2OrderServer).GetMyOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoreTestFromAccount2Order_GetMyOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoreTestFromAccount2OrderServer).GetMyOrder(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

// MoreTestFromAccount2Order_ServiceDesc is the grpc.ServiceDesc for MoreTestFromAccount2Order service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoreTestFromAccount2Order_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcdemo.MoreTestFromAccount2Order",
	HandlerType: (*MoreTestFromAccount2OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getMyOrder",
			Handler:    _MoreTestFromAccount2Order_GetMyOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcdemo.proto",
}
