// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: video.proto

package server

import (
	"context"

	"pilipili/app/video/rpc/internal/logic"
	"pilipili/app/video/rpc/internal/svc"
	"pilipili/app/video/rpc/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

// 1. 核心写操作
func (s *VideoServer) PublishVideo(ctx context.Context, in *video.PublishReq) (*video.PublishResp, error) {
	l := logic.NewPublishVideoLogic(ctx, s.svcCtx)
	return l.PublishVideo(in)
}

// 2. 核心读操作
func (s *VideoServer) GetVideoDetail(ctx context.Context, in *video.GetVideoDetailReq) (*video.GetVideoDetailResp, error) {
	l := logic.NewGetVideoDetailLogic(ctx, s.svcCtx)
	return l.GetVideoDetail(in)
}

// 3. 高并发批量读操作 (供推荐系统、API网关调用)
func (s *VideoServer) BatchGetVideo(ctx context.Context, in *video.BatchGetVideoReq) (*video.BatchGetVideoResp, error) {
	l := logic.NewBatchGetVideoLogic(ctx, s.svcCtx)
	return l.BatchGetVideo(in)
}

// 4. 获取实际播放流 (通常前端拿到视频详情后，再单独请求播放地址)
func (s *VideoServer) GetPlayUrl(ctx context.Context, in *video.GetPlayUrlReq) (*video.GetPlayUrlResp, error) {
	l := logic.NewGetPlayUrlLogic(ctx, s.svcCtx)
	return l.GetPlayUrl(in)
}
