// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: grpcdemo.proto

package server

import (
	"context"

	"grpcdemo/grpcdemo"
	"grpcdemo/internal/logic"
	"grpcdemo/internal/svc"
)

type MoreTestFromAccount2OrderServer struct {
	svcCtx *svc.ServiceContext
	grpcdemo.UnimplementedMoreTestFromAccount2OrderServer
}

func NewMoreTestFromAccount2OrderServer(svcCtx *svc.ServiceContext) *MoreTestFromAccount2OrderServer {
	return &MoreTestFromAccount2OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *MoreTestFromAccount2OrderServer) GetMyOrder(ctx context.Context, in *grpcdemo.User) (*grpcdemo.Orders, error) {
	l := logic.NewGetMyOrderLogic(ctx, s.svcCtx)
	return l.GetMyOrder(in)
}
