// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: comment.proto

package server

import (
	"context"

	"my-micro-service/app/comment/rpc/comment"
	"my-micro-service/app/comment/rpc/internal/logic"
	"my-micro-service/app/comment/rpc/internal/svc"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
	comment.UnimplementedCommentServer
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServer) CreateComment(ctx context.Context, in *comment.CreateCommentReq) (*comment.CreateCommentResp, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}
