// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: rpc/video.proto

package video

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Video_PublishVideo_FullMethodName   = "/video.Video/PublishVideo"
	Video_GetVideoDetail_FullMethodName = "/video.Video/GetVideoDetail"
	Video_BatchGetVideo_FullMethodName  = "/video.Video/BatchGetVideo"
	Video_GetPlayUrl_FullMethodName     = "/video.Video/GetPlayUrl"
)

// VideoClient is the client API for Video service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoClient interface {
	// 1. 核心写操作
	PublishVideo(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishResp, error)
	// 2. 核心读操作
	GetVideoDetail(ctx context.Context, in *GetVideoDetailReq, opts ...grpc.CallOption) (*GetVideoDetailResp, error)
	// 3. 高并发批量读操作 (供推荐系统、API网关调用)
	BatchGetVideo(ctx context.Context, in *BatchGetVideoReq, opts ...grpc.CallOption) (*BatchGetVideoResp, error)
	// 4. 获取实际播放流 (通常前端拿到视频详情后，再单独请求播放地址)
	GetPlayUrl(ctx context.Context, in *GetPlayUrlReq, opts ...grpc.CallOption) (*GetPlayUrlResp, error)
}

type videoClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoClient(cc grpc.ClientConnInterface) VideoClient {
	return &videoClient{cc}
}

func (c *videoClient) PublishVideo(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResp)
	err := c.cc.Invoke(ctx, Video_PublishVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetVideoDetail(ctx context.Context, in *GetVideoDetailReq, opts ...grpc.CallOption) (*GetVideoDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVideoDetailResp)
	err := c.cc.Invoke(ctx, Video_GetVideoDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) BatchGetVideo(ctx context.Context, in *BatchGetVideoReq, opts ...grpc.CallOption) (*BatchGetVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetVideoResp)
	err := c.cc.Invoke(ctx, Video_BatchGetVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetPlayUrl(ctx context.Context, in *GetPlayUrlReq, opts ...grpc.CallOption) (*GetPlayUrlResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayUrlResp)
	err := c.cc.Invoke(ctx, Video_GetPlayUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServer is the server API for Video service.
// All implementations must embed UnimplementedVideoServer
// for forward compatibility.
type VideoServer interface {
	// 1. 核心写操作
	PublishVideo(context.Context, *PublishReq) (*PublishResp, error)
	// 2. 核心读操作
	GetVideoDetail(context.Context, *GetVideoDetailReq) (*GetVideoDetailResp, error)
	// 3. 高并发批量读操作 (供推荐系统、API网关调用)
	BatchGetVideo(context.Context, *BatchGetVideoReq) (*BatchGetVideoResp, error)
	// 4. 获取实际播放流 (通常前端拿到视频详情后，再单独请求播放地址)
	GetPlayUrl(context.Context, *GetPlayUrlReq) (*GetPlayUrlResp, error)
	mustEmbedUnimplementedVideoServer()
}

// UnimplementedVideoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoServer struct{}

func (UnimplementedVideoServer) PublishVideo(context.Context, *PublishReq) (*PublishResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishVideo not implemented")
}
func (UnimplementedVideoServer) GetVideoDetail(context.Context, *GetVideoDetailReq) (*GetVideoDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVideoDetail not implemented")
}
func (UnimplementedVideoServer) BatchGetVideo(context.Context, *BatchGetVideoReq) (*BatchGetVideoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetVideo not implemented")
}
func (UnimplementedVideoServer) GetPlayUrl(context.Context, *GetPlayUrlReq) (*GetPlayUrlResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayUrl not implemented")
}
func (UnimplementedVideoServer) mustEmbedUnimplementedVideoServer() {}
func (UnimplementedVideoServer) testEmbeddedByValue()               {}

// UnsafeVideoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServer will
// result in compilation errors.
type UnsafeVideoServer interface {
	mustEmbedUnimplementedVideoServer()
}

func RegisterVideoServer(s grpc.ServiceRegistrar, srv VideoServer) {
	// If the following call panics, it indicates UnimplementedVideoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Video_ServiceDesc, srv)
}

func _Video_PublishVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).PublishVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_PublishVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).PublishVideo(ctx, req.(*PublishReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetVideoDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetVideoDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_GetVideoDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetVideoDetail(ctx, req.(*GetVideoDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_BatchGetVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).BatchGetVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_BatchGetVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).BatchGetVideo(ctx, req.(*BatchGetVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetPlayUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetPlayUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Video_GetPlayUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetPlayUrl(ctx, req.(*GetPlayUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Video_ServiceDesc is the grpc.ServiceDesc for Video service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Video_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.Video",
	HandlerType: (*VideoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishVideo",
			Handler:    _Video_PublishVideo_Handler,
		},
		{
			MethodName: "GetVideoDetail",
			Handler:    _Video_GetVideoDetail_Handler,
		},
		{
			MethodName: "BatchGetVideo",
			Handler:    _Video_BatchGetVideo_Handler,
		},
		{
			MethodName: "GetPlayUrl",
			Handler:    _Video_GetPlayUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/video.proto",
}
