// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: rpc/video.proto

package video

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 视频基本信息 (高度还原 B 站的 aid/bvid 概念，这里为简化统一用 id)
type VideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 视频ID (AV号)
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`          // UP主ID
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                                 // 视频标题
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`           // 封面图地址
	CategoryId    int32                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`    // 分区ID (如: 动画, 游戏)
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`                             // 视频简介
	PublishTime   int64                  `protobuf:"varint,7,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"` // 发布时间戳
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`                              // 状态: 0:审核中, 1:正常, 2:下架
	Duration      int32                  `protobuf:"varint,9,opt,name=duration,proto3" json:"duration,omitempty"`                          // 视频时长(秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_rpc_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{0}
}

func (x *VideoInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoInfo) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *VideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *VideoInfo) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *VideoInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *VideoInfo) GetPublishTime() int64 {
	if x != nil {
		return x.PublishTime
	}
	return 0
}

func (x *VideoInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VideoInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// 视频的统计数据 (实时变动)
type VideoStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewCount     int64                  `protobuf:"varint,1,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`             // 播放量
	DanmakuCount  int64                  `protobuf:"varint,2,opt,name=danmaku_count,json=danmakuCount,proto3" json:"danmaku_count,omitempty"`    // 弹幕数
	ReplyCount    int64                  `protobuf:"varint,3,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`          // 评论数
	LikeCount     int64                  `protobuf:"varint,4,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`             // 点赞数
	CoinCount     int64                  `protobuf:"varint,5,opt,name=coin_count,json=coinCount,proto3" json:"coin_count,omitempty"`             // 投币数
	FavoriteCount int64                  `protobuf:"varint,6,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"` // 收藏数
	ShareCount    int64                  `protobuf:"varint,7,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`          // 分享数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoStat) Reset() {
	*x = VideoStat{}
	mi := &file_rpc_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStat) ProtoMessage() {}

func (x *VideoStat) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStat.ProtoReflect.Descriptor instead.
func (*VideoStat) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{1}
}

func (x *VideoStat) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *VideoStat) GetDanmakuCount() int64 {
	if x != nil {
		return x.DanmakuCount
	}
	return 0
}

func (x *VideoStat) GetReplyCount() int64 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *VideoStat) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *VideoStat) GetCoinCount() int64 {
	if x != nil {
		return x.CoinCount
	}
	return 0
}

func (x *VideoStat) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *VideoStat) GetShareCount() int64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

// 播放流媒体信息
type PlayStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quality       string                 `protobuf:"bytes,1,opt,name=quality,proto3" json:"quality,omitempty"` // 画质 (如: "1080P", "720P")
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`         // 实际的 CDN 播放地址
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`   // 格式 (如: "mp4", "flv")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayStream) Reset() {
	*x = PlayStream{}
	mi := &file_rpc_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayStream) ProtoMessage() {}

func (x *PlayStream) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayStream.ProtoReflect.Descriptor instead.
func (*PlayStream) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{2}
}

func (x *PlayStream) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *PlayStream) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PlayStream) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// 投稿请求
type PublishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"` // 原始上传地址，后续会触发转码
	CategoryId    int32                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishReq) Reset() {
	*x = PublishReq{}
	mi := &file_rpc_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReq) ProtoMessage() {}

func (x *PublishReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReq.ProtoReflect.Descriptor instead.
func (*PublishReq) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{3}
}

func (x *PublishReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PublishReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublishReq) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *PublishReq) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *PublishReq) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *PublishReq) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type PublishResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResp) Reset() {
	*x = PublishResp{}
	mi := &file_rpc_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResp) ProtoMessage() {}

func (x *PublishResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResp.ProtoReflect.Descriptor instead.
func (*PublishResp) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{4}
}

func (x *PublishResp) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

// 获取视频详情请求 (包含统计数据)
type GetVideoDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoDetailReq) Reset() {
	*x = GetVideoDetailReq{}
	mi := &file_rpc_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoDetailReq) ProtoMessage() {}

func (x *GetVideoDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoDetailReq.ProtoReflect.Descriptor instead.
func (*GetVideoDetailReq) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{5}
}

func (x *GetVideoDetailReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type GetVideoDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *VideoInfo             `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Stat          *VideoStat             `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoDetailResp) Reset() {
	*x = GetVideoDetailResp{}
	mi := &file_rpc_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoDetailResp) ProtoMessage() {}

func (x *GetVideoDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoDetailResp.ProtoReflect.Descriptor instead.
func (*GetVideoDetailResp) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{6}
}

func (x *GetVideoDetailResp) GetInfo() *VideoInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetVideoDetailResp) GetStat() *VideoStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

// 批量获取视频信息 (非常重要：用于首页列表、UP主空间)
type BatchGetVideoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoIds      []int64                `protobuf:"varint,1,rep,packed,name=video_ids,json=videoIds,proto3" json:"video_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetVideoReq) Reset() {
	*x = BatchGetVideoReq{}
	mi := &file_rpc_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetVideoReq) ProtoMessage() {}

func (x *BatchGetVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetVideoReq.ProtoReflect.Descriptor instead.
func (*BatchGetVideoReq) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetVideoReq) GetVideoIds() []int64 {
	if x != nil {
		return x.VideoIds
	}
	return nil
}

type BatchGetVideoResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key 是 video_id，value 是视频信息
	Videos        map[int64]*VideoInfo `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetVideoResp) Reset() {
	*x = BatchGetVideoResp{}
	mi := &file_rpc_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetVideoResp) ProtoMessage() {}

func (x *BatchGetVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetVideoResp.ProtoReflect.Descriptor instead.
func (*BatchGetVideoResp) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGetVideoResp) GetVideos() map[int64]*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

// 获取播放地址请求 (通常需要鉴权，比如非大会员不给 1080p)
type GetPlayUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 谁在请求播放？(用于鉴权)
	QualityLimit  string                 `protobuf:"bytes,3,opt,name=quality_limit,json=qualityLimit,proto3" json:"quality_limit,omitempty"` // 期望的最高画质
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayUrlReq) Reset() {
	*x = GetPlayUrlReq{}
	mi := &file_rpc_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayUrlReq) ProtoMessage() {}

func (x *GetPlayUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayUrlReq.ProtoReflect.Descriptor instead.
func (*GetPlayUrlReq) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{9}
}

func (x *GetPlayUrlReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *GetPlayUrlReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPlayUrlReq) GetQualityLimit() string {
	if x != nil {
		return x.QualityLimit
	}
	return ""
}

type GetPlayUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*PlayStream          `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"` // 返回可用的播放流列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayUrlResp) Reset() {
	*x = GetPlayUrlResp{}
	mi := &file_rpc_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayUrlResp) ProtoMessage() {}

func (x *GetPlayUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayUrlResp.ProtoReflect.Descriptor instead.
func (*GetPlayUrlResp) Descriptor() ([]byte, []int) {
	return file_rpc_video_proto_rawDescGZIP(), []int{10}
}

func (x *GetPlayUrlResp) GetStreams() []*PlayStream {
	if x != nil {
		return x.Streams
	}
	return nil
}

var File_rpc_video_proto protoreflect.FileDescriptor

const file_rpc_video_proto_rawDesc = "" +
	"\n" +
	"\x0frpc/video.proto\x12\x05video\"\xfd\x01\n" +
	"\tVideoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x05R\n" +
	"categoryId\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12!\n" +
	"\fpublish_time\x18\a \x01(\x03R\vpublishTime\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1a\n" +
	"\bduration\x18\t \x01(\x05R\bduration\"\xf6\x01\n" +
	"\tVideoStat\x12\x1d\n" +
	"\n" +
	"view_count\x18\x01 \x01(\x03R\tviewCount\x12#\n" +
	"\rdanmaku_count\x18\x02 \x01(\x03R\fdanmakuCount\x12\x1f\n" +
	"\vreply_count\x18\x03 \x01(\x03R\n" +
	"replyCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\x04 \x01(\x03R\tlikeCount\x12\x1d\n" +
	"\n" +
	"coin_count\x18\x05 \x01(\x03R\tcoinCount\x12%\n" +
	"\x0efavorite_count\x18\x06 \x01(\x03R\rfavoriteCount\x12\x1f\n" +
	"\vshare_count\x18\a \x01(\x03R\n" +
	"shareCount\"P\n" +
	"\n" +
	"PlayStream\x12\x18\n" +
	"\aquality\x18\x01 \x01(\tR\aquality\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"\xb4\x01\n" +
	"\n" +
	"PublishReq\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x05R\n" +
	"categoryId\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\"(\n" +
	"\vPublishResp\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\".\n" +
	"\x11GetVideoDetailReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\"`\n" +
	"\x12GetVideoDetailResp\x12$\n" +
	"\x04info\x18\x01 \x01(\v2\x10.video.VideoInfoR\x04info\x12$\n" +
	"\x04stat\x18\x02 \x01(\v2\x10.video.VideoStatR\x04stat\"/\n" +
	"\x10BatchGetVideoReq\x12\x1b\n" +
	"\tvideo_ids\x18\x01 \x03(\x03R\bvideoIds\"\x9e\x01\n" +
	"\x11BatchGetVideoResp\x12<\n" +
	"\x06videos\x18\x01 \x03(\v2$.video.BatchGetVideoResp.VideosEntryR\x06videos\x1aK\n" +
	"\vVideosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.video.VideoInfoR\x05value:\x028\x01\"h\n" +
	"\rGetPlayUrlReq\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12#\n" +
	"\rquality_limit\x18\x03 \x01(\tR\fqualityLimit\"=\n" +
	"\x0eGetPlayUrlResp\x12+\n" +
	"\astreams\x18\x01 \x03(\v2\x11.video.PlayStreamR\astreams2\x84\x02\n" +
	"\x05Video\x125\n" +
	"\fPublishVideo\x12\x11.video.PublishReq\x1a\x12.video.PublishResp\x12E\n" +
	"\x0eGetVideoDetail\x12\x18.video.GetVideoDetailReq\x1a\x19.video.GetVideoDetailResp\x12B\n" +
	"\rBatchGetVideo\x12\x17.video.BatchGetVideoReq\x1a\x18.video.BatchGetVideoResp\x129\n" +
	"\n" +
	"GetPlayUrl\x12\x14.video.GetPlayUrlReq\x1a\x15.video.GetPlayUrlRespB\tZ\a./videob\x06proto3"

var (
	file_rpc_video_proto_rawDescOnce sync.Once
	file_rpc_video_proto_rawDescData []byte
)

func file_rpc_video_proto_rawDescGZIP() []byte {
	file_rpc_video_proto_rawDescOnce.Do(func() {
		file_rpc_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_video_proto_rawDesc), len(file_rpc_video_proto_rawDesc)))
	})
	return file_rpc_video_proto_rawDescData
}

var file_rpc_video_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_rpc_video_proto_goTypes = []any{
	(*VideoInfo)(nil),          // 0: video.VideoInfo
	(*VideoStat)(nil),          // 1: video.VideoStat
	(*PlayStream)(nil),         // 2: video.PlayStream
	(*PublishReq)(nil),         // 3: video.PublishReq
	(*PublishResp)(nil),        // 4: video.PublishResp
	(*GetVideoDetailReq)(nil),  // 5: video.GetVideoDetailReq
	(*GetVideoDetailResp)(nil), // 6: video.GetVideoDetailResp
	(*BatchGetVideoReq)(nil),   // 7: video.BatchGetVideoReq
	(*BatchGetVideoResp)(nil),  // 8: video.BatchGetVideoResp
	(*GetPlayUrlReq)(nil),      // 9: video.GetPlayUrlReq
	(*GetPlayUrlResp)(nil),     // 10: video.GetPlayUrlResp
	nil,                        // 11: video.BatchGetVideoResp.VideosEntry
}
var file_rpc_video_proto_depIdxs = []int32{
	0,  // 0: video.GetVideoDetailResp.info:type_name -> video.VideoInfo
	1,  // 1: video.GetVideoDetailResp.stat:type_name -> video.VideoStat
	11, // 2: video.BatchGetVideoResp.videos:type_name -> video.BatchGetVideoResp.VideosEntry
	2,  // 3: video.GetPlayUrlResp.streams:type_name -> video.PlayStream
	0,  // 4: video.BatchGetVideoResp.VideosEntry.value:type_name -> video.VideoInfo
	3,  // 5: video.Video.PublishVideo:input_type -> video.PublishReq
	5,  // 6: video.Video.GetVideoDetail:input_type -> video.GetVideoDetailReq
	7,  // 7: video.Video.BatchGetVideo:input_type -> video.BatchGetVideoReq
	9,  // 8: video.Video.GetPlayUrl:input_type -> video.GetPlayUrlReq
	4,  // 9: video.Video.PublishVideo:output_type -> video.PublishResp
	6,  // 10: video.Video.GetVideoDetail:output_type -> video.GetVideoDetailResp
	8,  // 11: video.Video.BatchGetVideo:output_type -> video.BatchGetVideoResp
	10, // 12: video.Video.GetPlayUrl:output_type -> video.GetPlayUrlResp
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rpc_video_proto_init() }
func file_rpc_video_proto_init() {
	if File_rpc_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_video_proto_rawDesc), len(file_rpc_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_video_proto_goTypes,
		DependencyIndexes: file_rpc_video_proto_depIdxs,
		MessageInfos:      file_rpc_video_proto_msgTypes,
	}.Build()
	File_rpc_video_proto = out.File
	file_rpc_video_proto_goTypes = nil
	file_rpc_video_proto_depIdxs = nil
}
