// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: video.proto

package videoclient

import (
	"context"

	"pilipili/app/video/rpc/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetVideoReq   = video.BatchGetVideoReq
	BatchGetVideoResp  = video.BatchGetVideoResp
	GetPlayUrlReq      = video.GetPlayUrlReq
	GetPlayUrlResp     = video.GetPlayUrlResp
	GetVideoDetailReq  = video.GetVideoDetailReq
	GetVideoDetailResp = video.GetVideoDetailResp
	PlayStream         = video.PlayStream
	PublishReq         = video.PublishReq
	PublishResp        = video.PublishResp
	VideoInfo          = video.VideoInfo
	VideoStat          = video.VideoStat

	Video interface {
		// 1. 核心写操作
		PublishVideo(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishResp, error)
		// 2. 核心读操作
		GetVideoDetail(ctx context.Context, in *GetVideoDetailReq, opts ...grpc.CallOption) (*GetVideoDetailResp, error)
		// 3. 高并发批量读操作 (供推荐系统、API网关调用)
		BatchGetVideo(ctx context.Context, in *BatchGetVideoReq, opts ...grpc.CallOption) (*BatchGetVideoResp, error)
		// 4. 获取实际播放流 (通常前端拿到视频详情后，再单独请求播放地址)
		GetPlayUrl(ctx context.Context, in *GetPlayUrlReq, opts ...grpc.CallOption) (*GetPlayUrlResp, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

// 1. 核心写操作
func (m *defaultVideo) PublishVideo(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.PublishVideo(ctx, in, opts...)
}

// 2. 核心读操作
func (m *defaultVideo) GetVideoDetail(ctx context.Context, in *GetVideoDetailReq, opts ...grpc.CallOption) (*GetVideoDetailResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetVideoDetail(ctx, in, opts...)
}

// 3. 高并发批量读操作 (供推荐系统、API网关调用)
func (m *defaultVideo) BatchGetVideo(ctx context.Context, in *BatchGetVideoReq, opts ...grpc.CallOption) (*BatchGetVideoResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.BatchGetVideo(ctx, in, opts...)
}

// 4. 获取实际播放流 (通常前端拿到视频详情后，再单独请求播放地址)
func (m *defaultVideo) GetPlayUrl(ctx context.Context, in *GetPlayUrlReq, opts ...grpc.CallOption) (*GetPlayUrlResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetPlayUrl(ctx, in, opts...)
}
